### ISSUE TITLE
Kubernetes client?

### ISSUE THREAD

**Issue by mhristache** [Arnavion/k8s-openapi-codegen#19]
Hi

Is there a kubernetes client that makes use of this project?

//Max

**Comment by Arnavion** [comment]
https://github.com/anowell/kubeclient-rs uses it. See https://github.com/anowell/kubeclient-rs/issues/4 for discussion about it.

**Comment by mhristache** [comment]
Ah, I thought kubeclient was abandoned. I will check it out again. Thanks
